# Here you can specify default options for TinyMCE across all controllers
#
 theme: advanced
 plugins:
  - table
  - fullscreen
  - emotions
 theme_advanced_buttons1: "bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,styleselect,formatselect,fontselect,fontsizeselect"
 theme_advanced_buttons2: "bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,|,forecolor,backcolor|,sub,sup,|,charmap,emotions"
 theme_advanced_buttons3: ""
 theme_advanced_toolbar_location : "top"
 theme_advanced_toolbar_location: "top"
 theme_advanced_toolbar_align: "left"
